### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [asiekierka/FoamFix#125]

**Comment by asiekierka** [comment]
Vanilla servers are a terrible reason. Vanilla+Forge+FoamFix will still consume significantly more RAM and CPU power than vanilla alone, or even vanilla plus LiteLoader.

When the 1.8.9 version was released, it was already missing a lot of contemporary fixes and features - this is because it was a quick release specifically created for low-end computer users to enjoy Thaumcraft 5 and Intangible, two content mods which will not likely make it post-1.8. That's it.

Out of scope. Sorry.

**Comment by Eddi2015** [comment]
and what about Vanilla+Forge+FoamFix instead of Vanilla+Forge?
I mean I'm playing a clientside pvp modpack and without foamfix it would consume more RAM (I think).
So that means foamfix helps. and that also means that the improvements should be ported. Correct me if I'm wrong. And yes I know it's not nice to support that old versions. Well the pvpvers need it...

**Comment by asiekierka** [comment]
"Should" and "need" are unwarranted here - I think "can" and "want" are more truthful.

Again, this is out of scope - I have no time to maintain the 1.8 version. Sorry.
