### ISSUE TITLE
Crash while setting PropertyDirection

### ISSUE THREAD

**Issue by Muirrum** [asiekierka/FoamFix#86]
https://github.com/simeonradivoev/MatterOverdrive/issues/680

User came to MO issue tracker with a FoamFix bug, said that it was an MO crash, definitely wasn't an MO crash.

**Comment by exaskye** [comment]
FoamFix overrides blockstates to increase performance, and as such seems to be implicated in crashes caused by a mod setting a property on a blockstate that doesn't support it.

The block in question only supports horizontal facings, and it seems ToughAsNails is attempting to give it a downward facing. The most likely cause of this is [you aren't limiting your metadata values to horizontal facings](https://github.com/simeonradivoev/MatterOverdrive/blob/0e0c00eab5a4c12a0eb2b444cef6fc2211326b8b/src/main/java/matteroverdrive/blocks/includes/MOBlock.java#L103), since you're using VALUES and ordinal() instead of getHorizontal(int) and getHorizontalIndex().

Considering that DOWN has an ordinal of 0, it seems ToughAsNails is attempting to use meta 0 as a default instead of checking getSubItems/getSubBlocks.

**Comment by Zarpyk** [comment]
> FoamFix overrides blockstates to increase performance, and as such seems to be implicated in crashes caused by a mod setting a property on a blockstate that doesn't support it.
> 
> The block in question only supports horizontal facings, and it seems ToughAsNails is attempting to give it a downward facing. The most likely cause of this is [you aren't limiting your metadata values to horizontal facings](https://github.com/simeonradivoev/MatterOverdrive/blob/0e0c00eab5a4c12a0eb2b444cef6fc2211326b8b/src/main/java/matteroverdrive/blocks/includes/MOBlock.java#L103), since you're using VALUES and ordinal() instead of getHorizontal(int) and getHorizontalIndex().
> 
> Considering that DOWN has an ordinal of 0, it seems ToughAsNails is attempting to use meta 0 as a default instead of checking getSubItems/getSubBlocks.

And is possible disable it in the config?
